project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
skip_untranslated_strings: 1
commit_message: '[ci skip]'
preserve_hierarchy: 1
files:
  - source: /app/javascript/mastodon/locales/en.json
    translation: /app/javascript/mastodon/locales/%two_letters_code%.json
  - source: /config/locales/en.yml
    translation: /config/locales/%two_letters_code%.yml
  - source: /config/locales/simple_form.en.yml
    translation: /config/locales/simple_form.%two_letters_code%.yml
  - source: /config/locales/activerecord.en.yml
    translation: /config/locales/activerecord.%two_letters_code%.yml
  - source: /config/locales/devise.en.yml
    translation: /config/locales/devise.%two_letters_code%.yml
  - source: /config/locales/doorkeeper.en.yml
    translation: /config/locales/doorkeeper.%two_letters_code%.yml
  - source: /app/javascript/flavours/glitch/locales/en.json
    translation: /app/javascript/flavours/glitch/locales/%two_letters_code%.json
  - source: /config/locales-glitch/en.yml
    translation: /config/locales-glitch/%two_letters_code%.yml
  - source: /config/locales-glitch/simple_form.en.yml
    translation: /config/locales-glitch/simple_form.%two_letters_code%.yml
