name: Build Latest Container Images
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - '*'

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    uses: ./.github/workflows/build-container-image.yml
    with:
      file_to_build: Dockerfile
      platforms: linux/amd64,linux/arm64
      use_native_arm64_builder: true
      push_to_images: |
        ghcr.io/${{ github.repository_owner }}/mastodon
      flavor: |
        latest=auto
      tags: |
        type=raw,value=latest,enable={{is_default_branch}}
        type=edge,branch=main
    secrets: inherit
  
  build-image-streaming:
    uses: ./.github/workflows/build-container-image.yml
    with:
      file_to_build: streaming/Dockerfile
      platforms: linux/amd64,linux/arm64
      use_native_arm64_builder: true
      push_to_images: |
        ghcr.io/${{ github.repository_owner }}/mastodon-streaming
      flavor: |
        latest=auto
      tags: |
        type=raw,value=latest,enable={{is_default_branch}}
        type=edge,branch=main
    secrets: inherit
