name: Container CI
on:
  workflow_call:
    inputs:
      cache:
        type: boolean
        default: true
      push_to_images:
        type: string
      version_prerelease:
        type: string
      version_metadata:
        type: string
      flavor:
        type: string
      tags:
        type: string
      labels:
        type: string
      file_to_build:
        type: string

# This builds multiple images with one runner each, allowing us to build for multiple architectures
# using Github's runners.
# The two-step process is adapted form:
# https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners
jobs:
  # Build each (amd64 and arm64) image separately
  build-image:
    runs-on: ${{ startsWith(matrix.platform, 'linux/arm') && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - uses: actions/checkout@v4

      - name: Integrate BirdUI Theme - Checkout
        run: |
          mkdir -p app/javascript/styles/mastodon-bird-ui
          mkdir -p app/javascript/flavours/glitch/styles/mastodon-bird-ui
          wget https://raw.githubusercontent.com/ronilaukkarinen/mastodon-bird-ui/main/layout-single-column.css -O app/javascript/styles/mastodon-bird-ui/layout-single-column.scss
          wget https://raw.githubusercontent.com/ronilaukkarinen/mastodon-bird-ui/main/layout-multiple-columns.css -O app/javascript/styles/mastodon-bird-ui/layout-multiple-columns.scss
          wget https://raw.githubusercontent.com/TheEssem/glitch-bird-ui/master/layout-single-column.css -O app/javascript/flavours/glitch/styles/mastodon-bird-ui/layout-single-column.scss
          wget https://raw.githubusercontent.com/TheEssem/glitch-bird-ui/master/layout-multiple-columns.css -O app/javascript/flavours/glitch/styles/mastodon-bird-ui/layout-multiple-columns.scss
          sed -i 's/theme-contrast/theme-mastodon-bird-ui-contrast/g' app/javascript/styles/mastodon-bird-ui/layout-single-column.scss
          sed -i 's/theme-mastodon-light/theme-mastodon-bird-ui-light/g' app/javascript/styles/mastodon-bird-ui/layout-single-column.scss
          sed -i 's/theme-contrast/theme-mastodon-bird-ui-contrast/g' app/javascript/styles/mastodon-bird-ui/layout-multiple-columns.scss
          sed -i 's/theme-mastodon-light/theme-mastodon-bird-ui-light/g' app/javascript/styles/mastodon-bird-ui/layout-multiple-columns.scss
          sed -i 's/theme-contrast/theme-mastodon-bird-ui-contrast/g' app/javascript/flavours/glitch/styles/mastodon-bird-ui/layout-single-column.scss
          sed -i 's/theme-mastodon-light/theme-mastodon-bird-ui-light/g' app/javascript/flavours/glitch/styles/mastodon-bird-ui/layout-single-column.scss
          sed -i 's/theme-contrast/theme-mastodon-bird-ui-contrast/g' app/javascript/flavours/glitch/styles/mastodon-bird-ui/layout-multiple-columns.scss
          sed -i 's/theme-mastodon-light/theme-mastodon-bird-ui-light/g' app/javascript/flavours/glitch/styles/mastodon-bird-ui/layout-multiple-columns.scss
          mkdir -p app/javascript/skins/vanilla/birdui-contrast
          mkdir -p app/javascript/skins/vanilla/birdui-light
          mkdir -p app/javascript/skins/vanilla/birdui-dark
          mkdir -p app/javascript/skins/glitch/birdui-contrast
          mkdir -p app/javascript/skins/glitch/birdui-light
          mkdir -p app/javascript/skins/glitch/birdui-dark
          echo -e "@import 'styles/contrast';\n@import 'styles/mastodon-bird-ui/layout-single-column.scss';\n@import 'styles/mastodon-bird-ui/layout-multiple-columns.scss';" > app/javascript/skins/vanilla/birdui-contrast/common.scss
          echo -e "@import 'styles/mastodon-light';\n@import 'styles/mastodon-bird-ui/layout-single-column.scss';\n@import 'styles/mastodon-bird-ui/layout-multiple-columns.scss';" > app/javascript/skins/vanilla/birdui-light/common.scss
          echo -e "@import 'styles/application';\n@import 'styles/mastodon-bird-ui/layout-single-column.scss';\n@import 'styles/mastodon-bird-ui/layout-multiple-columns.scss';" > app/javascript/skins/vanilla/birdui-dark/common.scss
          echo -e "@import 'flavours/glitch/styles/contrast';\n@import 'flavours/glitch/styles/mastodon-bird-ui/layout-single-column.scss';\n@import 'flavours/glitch/styles/mastodon-bird-ui/layout-multiple-columns.scss';" > app/javascript/skins/glitch/birdui-contrast/common.scss
          echo -e "@import 'flavours/glitch/styles/mastodon-light';\n@import 'flavours/glitch/styles/mastodon-bird-ui/layout-single-column.scss';\n@import 'flavours/glitch/styles/mastodon-bird-ui/layout-multiple-columns.scss';" > app/javascript/skins/glitch/birdui-light/common.scss
          echo -e "@import 'flavours/glitch/styles/index';\n@import 'flavours/glitch/styles/mastodon-bird-ui/layout-single-column.scss';\n@import 'flavours/glitch/styles/mastodon-bird-ui/layout-multiple-columns.scss';" > app/javascript/skins/glitch/birdui-dark/common.scss
          echo -e "en:\n  skins:\n    vanilla:\n      birdui-contrast: Bird UI (contrast)" > app/javascript/skins/vanilla/birdui-contrast/names.yml
          echo -e "en:\n  skins:\n    vanilla:\n      birdui-light: Bird UI (light)" > app/javascript/skins/vanilla/birdui-light/names.yml
          echo -e "en:\n  skins:\n    vanilla:\n      birdui-dark: Bird UI (dark)" > app/javascript/skins/vanilla/birdui-dark/names.yml
          echo -e "en:\n  skins:\n    glitch:\n      birdui-contrast: Bird UI (contrast)" > app/javascript/skins/glitch/birdui-contrast/names.yml
          echo -e "en:\n  skins:\n    glitch:\n      birdui-light: Bird UI (light)" > app/javascript/skins/glitch/birdui-light/names.yml
          echo -e "en:\n  skins:\n    glitch:\n      birdui-dark: Bird UI (dark)" > app/javascript/skins/glitch/birdui-dark/names.yml

      - name: Integrate Modern Theme - Checkout
        run: |
          mkdir -p app/javascript/styles/modern
          mkdir -p app/javascript/flavours/glitch/styles/modern
          wget https://git.gay/freeplay/Mastodon-Modern/raw/branch/waf/modern.css -O app/javascript/styles/modern/style.scss
          cp app/javascript/styles/modern/style.scss app/javascript/flavours/glitch/styles/modern/style.scss
          wget https://git.gay/freeplay/Mastodon-Modern/raw/branch/waf/glitch-fixes.css -O app/javascript/flavours/glitch/styles/modern/glitch-fixes.scss
          echo -e "@import 'mastodon/variables';\n@import 'application';\n@import 'modern/style';" > app/javascript/styles/modern-dark.scss
          echo -e "@import 'mastodon-light/variables';\n@import 'application';\n@import 'modern/style';\n@import 'mastodon-light/diff';" > app/javascript/styles/modern-light.scss
          echo -e "@import 'contrast/variables';\n@import 'application';\n@import 'modern/style';\n@import 'contrast/diff';" > app/javascript/styles/modern-contrast.scss
          echo -e "@import 'variables';\n@import 'index';\n@import 'modern/style';\n@import 'modern/glitch-fixes';" > app/javascript/flavours/glitch/styles/modern-dark.scss
          echo -e "@import 'mastodon-light/variables';\n@import 'index';\n@import 'modern/style';\n@import 'modern/glitch-fixes';\n@import 'mastodon-light/diff';" > app/javascript/flavours/glitch/styles/modern-light.scss
          echo -e "@import 'contrast/variables';\n@import 'index';\n@import 'modern/style';\n@import 'modern/glitch-fixes';\n@import 'contrast/diff';" > app/javascript/flavours/glitch/styles/modern-contrast.scss
          mkdir -p app/javascript/skins/vanilla/modern-dark
          mkdir -p app/javascript/skins/vanilla/modern-light
          mkdir -p app/javascript/skins/vanilla/modern-contrast
          mkdir -p app/javascript/skins/glitch/modern-dark
          mkdir -p app/javascript/skins/glitch/modern-light
          mkdir -p app/javascript/skins/glitch/modern-contrast
          echo -e "@import 'styles/modern-dark';" > app/javascript/skins/vanilla/modern-dark/common.scss
          echo -e "@import 'styles/modern-light';" > app/javascript/skins/vanilla/modern-light/common.scss
          echo -e "@import 'styles/modern-contrast';" > app/javascript/skins/vanilla/modern-contrast/common.scss
          echo -e "@import 'flavours/glitch/styles/modern-dark';" > app/javascript/skins/glitch/modern-dark/common.scss
          echo -e "@import 'flavours/glitch/styles/modern-light';" > app/javascript/skins/glitch/modern-light/common.scss
          echo -e "@import 'flavours/glitch/styles/modern-contrast';" > app/javascript/skins/glitch/modern-contrast/common.scss
          echo -e "en:\n  skins:\n    vanilla:\n      modern-dark: Mastodon Modern (dark)" > app/javascript/skins/vanilla/modern-dark/names.yml
          echo -e "en:\n  skins:\n    vanilla:\n      modern-light: Mastodon Modern (light)" > app/javascript/skins/vanilla/modern-light/names.yml
          echo -e "en:\n  skins:\n    vanilla:\n      modern-contrast: Mastodon Modern (contrast)" > app/javascript/skins/vanilla/modern-contrast/names.yml
          echo -e "en:\n  skins:\n    glitch:\n      modern-dark: Mastodon Modern (dark)" > app/javascript/skins/glitch/modern-dark/names.yml
          echo -e "en:\n  skins:\n    glitch:\n      modern-light: Mastodon Modern (light)" > app/javascript/skins/glitch/modern-light/names.yml
          echo -e "en:\n  skins:\n    glitch:\n      modern-contrast: Mastodon Modern (contrast)" > app/javascript/skins/glitch/modern-contrast/names.yml

      # Note: TangerineUI only supports Vanilla favour
      - name: Integrate TangerineUI - Checkout
        run: |
          git clone https://github.com/nileane/TangerineUI-for-Mastodon tangerine
          cp -r tangerine/mastodon/app/javascript/styles/* app/javascript/styles
          cp -r tangerine/mastodon/app/javascript/skins/vanilla/* app/javascript/skins/vanilla
          rm -rf tangerine

      - name: Apply Emoji Reaction Patch
        continue-on-error: true
        run: |
          wget https://patch-diff.githubusercontent.com/raw/glitch-soc/mastodon/pull/2462.patch -O /tmp/emoji-reaction.patch
          git apply /tmp/emoji-reaction.patch
          rm /tmp/emoji-reaction.patch

      - uses: docker/setup-qemu-action@v3
        if: contains(inputs.platforms, 'linux/arm64') && !inputs.use_native_arm64_builder
      - name: Prepare
        env:
          PUSH_TO_IMAGES: ${{ inputs.push_to_images }}
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
          # Transform multi-line variable into comma-separated variable
          image_names=${PUSH_TO_IMAGES//$'\n'/,}
          echo "IMAGE_NAMES=${image_names%,}" >> $GITHUB_ENV

      - uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Log in to Docker Hub
        if: contains(inputs.push_to_images, 'tootsuite')
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the GitHub Container registry
        if: contains(inputs.push_to_images, 'ghcr.io')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        if: ${{ inputs.push_to_images != '' }}
        with:
          images: ${{ inputs.push_to_images }}
          flavor: ${{ inputs.flavor }}
          labels: ${{ inputs.labels }}

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.file_to_build }}
          build-args: |
            MASTODON_VERSION_PRERELEASE=${{ inputs.version_prerelease }}
            MASTODON_VERSION_METADATA=${{ inputs.version_metadata }}
            SOURCE_COMMIT=${{ github.sha }}
          platforms: ${{ matrix.platform }}
          provenance: false
          push: ${{ inputs.push_to_images != '' }}
          cache-from: ${{ inputs.cache && 'type=gha' || '' }}
          cache-to: ${{ inputs.cache && 'type=gha,mode=max' || '' }}
          outputs: type=image,"name=${{ env.IMAGE_NAMES }}",push-by-digest=true,name-canonical=true,push=${{ inputs.push_to_images != '' }}

      - name: Export digest
        if: ${{ inputs.push_to_images != '' }}
        run: |
          mkdir -p "${{ runner.temp }}/digests"
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        if: ${{ inputs.push_to_images != '' }}
        uses: actions/upload-artifact@v4
        with:
          # `hashFiles` is used to disambiguate between streaming and non-streaming images
          name: digests-${{ hashFiles(inputs.file_to_build) }}-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  # Then merge the docker images into a single one
  merge-images:
    if: ${{ inputs.push_to_images != '' }}
    runs-on: ubuntu-24.04
    needs:
      - build-image

    env:
      PUSH_TO_IMAGES: ${{ inputs.push_to_images }}

    steps:
      - uses: actions/checkout@v4

      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          # `hashFiles` is used to disambiguate between streaming and non-streaming images
          pattern: digests-${{ hashFiles(inputs.file_to_build) }}-*
          merge-multiple: true

      - name: Log in to Docker Hub
        if: contains(inputs.push_to_images, 'tootsuite')
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the GitHub Container registry
        if: contains(inputs.push_to_images, 'ghcr.io')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        if: ${{ inputs.push_to_images != '' }}
        with:
          images: ${{ inputs.push_to_images }}
          flavor: ${{ inputs.flavor }}
          tags: ${{ inputs.tags }}
          labels: ${{ inputs.labels }}

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          echo "$PUSH_TO_IMAGES" | xargs -I{} \
            docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
              $(printf '{}@sha256:%s ' *)

      - name: Inspect image
        run: |
          echo "$PUSH_TO_IMAGES" | xargs -i{} \
            docker buildx imagetools inspect {}:${{ steps.meta.outputs.version }}
